(part "MS580305BA01-00"
    (packageRef "MS580305BA")
    (interface
        (port "1" (symbPinId 1) (portName "SCLK") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CSB") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VDD") (portType INOUT))
        (port "6" (symbPinId 6) (portName "PS") (portType INOUT))
        (port "7" (symbPinId 7) (portName "SDI/SDA") (portType INOUT))
        (port "8" (symbPinId 8) (portName "SDO") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "824-MS580305BA01-00")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Measurement-Specialties/MS580305BA01-00?qs=oFx6pF86PmAdNB98SCP3Rg%3D%3D")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "MS580305BA01-00")
    (property "Description" "Dimensions: Dimensions 6.2 x 6.4 MM | Dimensions .24 x .25 INCH | Electrical Characteristics: Board Level Pressure Sensor Supply Voltage 1.8  3.6 V | Operation/Application: Pressure 5000 MBAR | Resolution .036 | Board Level Pressure Sensor Accuracy +/-120mbar | Output/Span 24 bit ADC | Other: Sensor Options No Option | Packaging Features: Board Level Pressure Sensor Package Surface Mountable | Product Type Features: Board Level Pressure Sensor Style Absolute | Board Level Pressure Sensor Type Digital Pres")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=MS5803-05BA&DocType=Data%20Sheet&DocLang=English&PartCntxt=MS580305BA01-00&DocFormat=pdf")
    (property "symbolName1" "MS580305BA01-00")
)
